# Generated by Django 4.1.7 on 2023-11-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='actual',
        ),
    ]
