# Generated by Django 4.1.7 on 2023-11-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0002_remove_check_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='Actual',
            new_name='Actual_1',
        ),
        migrations.AddField(
            model_name='inspection',
            name='Actual_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='Actual_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='Actual_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='Actual_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='Observation',
            field=models.CharField(blank=True, choices=[('Ok', 'Ok'), ('Not_ok', 'Not_ok')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='Photos'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='check_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insp.check'),
        ),
    ]
