# Generated by Django 4.1.7 on 2023-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0009_inspection_approved_by_alter_inspection_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_code',
            name='Machine',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project_code',
            name='Operator',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project_code',
            name='Qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_code',
            name='RM_Coil_No',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project_code',
            name='Work_order_No',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
