# Generated by Django 4.1.7 on 2023-11-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0013_check_checking_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='spec_min',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
