# Generated by Django 4.1.7 on 2023-11-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0014_alter_check_spec_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='Requirement',
            field=models.CharField(blank=True, help_text='Checking_method: Visual', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='spec_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
