# Generated by Django 4.1.7 on 2023-12-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0016_alter_check_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_No',
        ),
    ]
