# Generated by Django 4.1.7 on 2023-12-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0017_remove_part_part_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(blank=True, max_length=256, null=True)),
                ('part_name', models.CharField(blank=True, max_length=256, null=True)),
                ('Drawing', models.FileField(blank=True, max_length=256, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='project_code',
            name='part_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insp.part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insp.part_group'),
        ),
    ]
